version: '3.8'

services:
  # Nosso servidor web estático
  web:
    image: nginx:alpine
    container_name: devtech_web
    ports:
      # Expõe o servidor na porta 8080 do seu computador
      - "8080:80"
    volumes:
      # 1. Monta o código-fonte (HTML/JS) para dentro do container
      - ./src:/usr/share/nginx/html
      
      # 2. Monta nosso arquivo de configuração customizado do Nginx
      - ./nginx.conf:/etc/nginx/conf.d/default.conf