version: '3.8'

services:
  web:
    image: nginx:alpine
    container_name: devtech_web
    ports:
      # servidor na porta 8080
      - "8080:80"
    volumes:
      # código-fonte (HTML/JS) para o container
      - ./src:/usr/share/nginx/html
      
      # arquivo de configuração customizado do Nginx
      - ./nginx.conf:/etc/nginx/conf.d/default.conf